from django.urls import path

from tasks.views import (
    board_create,
    board_delete,
    board_detail,
    board_export_csv,
    board_list,
    board_tag_create,
    board_tag_delete,
    board_tag_update,
    board_task_list_create,
    board_task_list_delete,
    board_task_list_update,
    board_task_move,
    board_update,
    task_create,
    task_delete,
    task_detail,
    task_list,
    task_update,
)

urlpatterns = [
    path("", board_list, name="board_list"),
    path("boards/create/", board_create, name="board_create"),
    path("boards/<int:pk>/edit/", board_update, name="board_update"),
    path("boards/<int:pk>/delete/", board_delete, name="board_delete"),
    path("boards/<int:pk>/export/csv/", board_export_csv, name="board_export_csv"),
    path("boards/<int:pk>/", board_detail, name="board_detail"),
    path("boards/<int:board_pk>/tags/create/", board_tag_create, name="board_tag_create"),
    path("boards/<int:board_pk>/tags/<int:pk>/edit/", board_tag_update, name="board_tag_update"),
    path("boards/<int:board_pk>/tags/<int:pk>/delete/", board_tag_delete, name="board_tag_delete"),
    path("boards/<int:board_pk>/lists/create/", board_task_list_create, name="board_task_list_create"),
    path("boards/<int:board_pk>/lists/<int:pk>/edit/", board_task_list_update, name="board_task_list_update"),
    path("boards/<int:board_pk>/lists/<int:pk>/delete/", board_task_list_delete, name="board_task_list_delete"),
    path("boards/<int:board_pk>/tasks/create/", task_create, name="board_task_create"),
    path("boards/<int:board_pk>/tasks/<int:pk>/move/", board_task_move, name="board_task_move"),
    path("tasks/", task_list, name="task_list"),
    path("tasks/create/", task_create, name="task_create"),
    path("tasks/<int:pk>/", task_detail, name="task_detail"),
    path("tasks/<int:pk>/edit/", task_update, name="task_update"),
    path("tasks/<int:pk>/delete/", task_delete, name="task_delete"),
]
