"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qsl, unquote, urlparse

from django.core.exceptions import ImproperlyConfigured
from tasks.demo_data import DEFAULT_DEMO_PASSWORD

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(env_path):
    if not env_path.exists():
        return

    for raw_line in env_path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()

        if value and value[0] == value[-1] and value[0] in {'"', "'"}:
            value = value[1:-1]

        os.environ.setdefault(key, value)


def _get_bool_env(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _get_list_env(name, default=None):
    if default is None:
        default = []

    value = os.environ.get(name)
    if value is None:
        return default

    return [item.strip() for item in value.split(",") if item.strip()]


def _normalize_db_engine(value):
    aliases = {
        "sqlite": "django.db.backends.sqlite3",
        "sqlite3": "django.db.backends.sqlite3",
        "django.db.backends.sqlite3": "django.db.backends.sqlite3",
        "postgres": "django.db.backends.postgresql",
        "postgresql": "django.db.backends.postgresql",
        "psql": "django.db.backends.postgresql",
        "django.db.backends.postgresql": "django.db.backends.postgresql",
    }
    return aliases.get(value, value)


def _resolve_sqlite_name(raw_name):
    if not raw_name:
        return BASE_DIR / "db.sqlite3"

    if raw_name == ":memory:":
        return raw_name

    sqlite_path = Path(raw_name)
    if sqlite_path.is_absolute():
        return sqlite_path

    return BASE_DIR / sqlite_path


def _database_config_from_url(database_url):
    parsed_url = urlparse(database_url)
    engine = _normalize_db_engine(parsed_url.scheme)

    if engine == "django.db.backends.sqlite3":
        sqlite_name = unquote(f"{parsed_url.netloc}{parsed_url.path}")
        if sqlite_name.startswith("//"):
            sqlite_name = sqlite_name[1:]
        else:
            sqlite_name = sqlite_name.lstrip("/")
        return {
            "ENGINE": engine,
            "NAME": _resolve_sqlite_name(sqlite_name),
        }

    if engine != "django.db.backends.postgresql":
        raise ValueError(f"Unsupported DATABASE_URL scheme: {parsed_url.scheme}")

    database_config = {
        "ENGINE": engine,
        "NAME": unquote(parsed_url.path.lstrip("/")),
        "USER": unquote(parsed_url.username or ""),
        "PASSWORD": unquote(parsed_url.password or ""),
        "HOST": parsed_url.hostname or "",
        "PORT": str(parsed_url.port or ""),
    }

    options = dict(parse_qsl(parsed_url.query, keep_blank_values=False))
    if options:
        database_config["OPTIONS"] = options

    return database_config


def _build_database_config():
    database_url = os.environ.get("DATABASE_URL", "").strip()
    if database_url:
        return _database_config_from_url(database_url)

    explicit_engine = os.environ.get("DB_ENGINE", "").strip()
    if explicit_engine:
        engine = _normalize_db_engine(explicit_engine)
        if engine == "django.db.backends.sqlite3":
            return {
                "ENGINE": engine,
                "NAME": _resolve_sqlite_name(os.environ.get("DB_NAME", "db.sqlite3")),
            }

        return {
            "ENGINE": engine,
            "NAME": os.environ.get("DB_NAME", ""),
            "USER": os.environ.get("DB_USER", ""),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get("DB_HOST", ""),
            "PORT": os.environ.get("DB_PORT", ""),
        }

    return {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }


_load_env_file(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

DEFAULT_SECRET_KEY = (
    "django-insecure-0=cp6*cwgyvmd@lc6*+6#2*%xay#**)@%y(2w(v%4@jr3*m^!n"
)
INSECURE_SECRET_KEY_VALUES = {
    "",
    "change-me",
    "django-insecure-change-me",
    DEFAULT_SECRET_KEY,
}

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _get_bool_env("DEBUG", default=True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", DEFAULT_SECRET_KEY).strip() or DEFAULT_SECRET_KEY

ALLOWED_HOSTS = _get_list_env("ALLOWED_HOSTS", default=[])
CSRF_TRUSTED_ORIGINS = _get_list_env("CSRF_TRUSTED_ORIGINS", default=[])

if not DEBUG and SECRET_KEY in INSECURE_SECRET_KEY_VALUES:
    raise ImproperlyConfigured("Set a real SECRET_KEY when DEBUG=False.")

if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        "Set ALLOWED_HOSTS when DEBUG=False."
    )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tasks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": _build_database_config()
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"


# Authentication
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "board_list"
LOGOUT_REDIRECT_URL = "login"


# Demo user credentials
DEMO_USER_PASSWORD = os.environ.get("DEMO_USER_PASSWORD", DEFAULT_DEMO_PASSWORD)
